In [2]:
import numpy as np
import pandas as pd

In [11]:
dict1 = {"name":["harry","rohan","ayush","anshul"],"marks":[92,34,56,76],"city":["Bangalore","Kolkata","Jaipur","Delhi"]}

In [12]:
df = pd.DataFrame(dict1)

In [13]:
df

     name  marks       city
0   harry     92  Bangalore
1   rohan     34    Kolkata
2   ayush     56     Jaipur
3  anshul     76      Delhi

In [14]:
df.to_csv('friends.csv')

In [15]:
df.to_csv('friends.csv',index=False)

In [16]:
df.head(1)

    name  marks       city
0  harry     92  Bangalore

In [17]:
df.tail(1)

     name  marks   city
3  anshul     76  Delhi

In [18]:
df.describe()

          marks
count   4.00000
mean   64.50000
std    25.10644
min    34.00000
25%    50.50000
50%    66.00000
75%    80.00000
max    92.00000

In [19]:
testdf = pd.read_csv('pandas_test.csv')

In [20]:
testdf['Variable_name']

0                                           Total income
1        Sales, government funding, grants and subsidies
2                      Interest, dividends and donations
3                                   Non-operating income
4                                      Total expenditure
                              ...
55615                                        Quick ratio
55616                Margin on sales of goods for resale
55617                                   Return on equity
55618                             Return on total assets
55619                              Liabilities structure
Name: Variable_name, Length: 55620, dtype: object

In [21]:
testdf['Variable_name'][1]

'Sales, government funding, grants and subsidies'

In [23]:
testdf.to_csv("changed_value.csv")

In [24]:
df.index = ['first','second','third','fourth']

In [25]:
df

          name  marks       city
first    harry     92  Bangalore
second   rohan     34    Kolkata
third    ayush     56     Jaipur
fourth  anshul     76      Delhi

In [26]:
ser = pd.Series(np.random.rand(34))

In [27]:
ser

0     0.585762
1     0.450238
2     0.198212
3     0.388204
4     0.233900
5     0.540667
6     0.600742
7     0.750375
8     0.780009
9     0.088769
10    0.518973
11    0.218415
12    0.646983
13    0.118979
14    0.398701
15    0.035873
16    0.467366
17    0.967677
18    0.240082
19    0.164803
20    0.094235
21    0.982982
22    0.030227
23    0.543949
24    0.725200
25    0.409502
26    0.104984
27    0.543124
28    0.737186
29    0.535621
30    0.724838
31    0.716080
32    0.342697
33    0.234089
dtype: float64

In [3]:
newdf = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [5]:
newdf.columns = list("ABCDE")

In [6]:
#as per the new pandas update, a series can't upgrade to object dtype if you just change the datatype of any one value.
#you need to manually do this and then you can have multiple values in that series.
newdf['A'] = newdf['A'].astype(object)
newdf.loc[2, 'A'] = "Ayush"

In [7]:
newdf

            A         B         C         D         E
0    0.788687  0.600837  0.532238  0.302723  0.115555
1    0.382473  0.276835  0.670707  0.201305  0.728110
2       Ayush  0.689297  0.162800  0.011255  0.439908
3    0.821584  0.023659  0.979987  0.282774  0.155972
4    0.658512  0.851439  0.118980  0.708024  0.985464
..        ...       ...       ...       ...       ...
329  0.258052  0.083932  0.083910  0.091362  0.569204
330  0.370393  0.810245  0.362469  0.203396  0.452469
331  0.406575  0.490045  0.492634  0.669368  0.024355
332  0.257022  0.572599  0.404611  0.880945  0.426001
333  0.663787  0.335064  0.499930  0.813554  0.042426

[334 rows x 5 columns]

In [8]:
newdf.dtypes

A     object
B    float64
C    float64
D    float64
E    float64
dtype: object

In [9]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [10]:
newdf.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [11]:
newdf.to_numpy()

array([[0.788686714436463, 0.600837483055396, 0.5322376655212612,
        0.30272270627484876, 0.11555510944886738],
       [0.3824733634714109, 0.27683525379886265, 0.6707067086376755,
        0.20130541973052307, 0.7281102951225128],
       ['Ayush', 0.6892969199147526, 0.16279995944100267,
        0.011255362583384887, 0.4399082058274969],
       ...,
       [0.40657486144473287, 0.4900448491929199, 0.49263446793856547,
        0.6693675547861814, 0.02435523682668317],
       [0.2570220760708729, 0.5725992505670313, 0.40461132673349287,
        0.8809449236405776, 0.4260008322761215],
       [0.6637871239242656, 0.33506386260958965, 0.4999298854863019,
        0.8135542744124054, 0.04242600868147284]],
      shape=(334, 5), dtype=object)

In [12]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
A,0.788687,0.382473,Ayush,0.821584,0.658512,0.549551,0.643869,0.4746,0.773669,0.812275,...,0.134287,0.796156,0.136606,0.391381,0.324299,0.258052,0.370393,0.406575,0.257022,0.663787
B,0.600837,0.276835,0.689297,0.023659,0.851439,0.567473,0.27796,0.402154,0.365969,0.986045,...,0.971223,0.861162,0.90722,0.821261,0.202162,0.083932,0.810245,0.490045,0.572599,0.335064
C,0.532238,0.670707,0.1628,0.979987,0.11898,0.976715,0.08497,0.573117,0.791882,0.240203,...,0.985555,0.855032,0.409721,0.242945,0.40591,0.08391,0.362469,0.492634,0.404611,0.49993
D,0.302723,0.201305,0.011255,0.282774,0.708024,0.672992,0.592636,0.588132,0.854105,0.121623,...,0.430196,0.118135,0.180857,0.859496,0.373743,0.091362,0.203396,0.669368,0.880945,0.813554
E,0.115555,0.72811,0.439908,0.155972,0.985464,0.275604,0.479976,0.148752,0.592197,0.568039,...,0.796247,0.548893,0.821502,0.048049,0.676513,0.569204,0.452469,0.024355,0.426001,0.042426

In [13]:
newdf.sort_index(axis=0, ascending=False)

            A         B         C         D         E
333  0.663787  0.335064  0.499930  0.813554  0.042426
332  0.257022  0.572599  0.404611  0.880945  0.426001
331  0.406575  0.490045  0.492634  0.669368  0.024355
330  0.370393  0.810245  0.362469  0.203396  0.452469
329  0.258052  0.083932  0.083910  0.091362  0.569204
..        ...       ...       ...       ...       ...
4    0.658512  0.851439  0.118980  0.708024  0.985464
3    0.821584  0.023659  0.979987  0.282774  0.155972
2       Ayush  0.689297  0.162800  0.011255  0.439908
1    0.382473  0.276835  0.670707  0.201305  0.728110
0    0.788687  0.600837  0.532238  0.302723  0.115555

[334 rows x 5 columns]

In [14]:
newdf2 = newdf

In [15]:
newdf2 = newdf.copy()

In [16]:
newdf

            A         B         C         D         E
0    0.788687  0.600837  0.532238  0.302723  0.115555
1    0.382473  0.276835  0.670707  0.201305  0.728110
2       Ayush  0.689297  0.162800  0.011255  0.439908
3    0.821584  0.023659  0.979987  0.282774  0.155972
4    0.658512  0.851439  0.118980  0.708024  0.985464
..        ...       ...       ...       ...       ...
329  0.258052  0.083932  0.083910  0.091362  0.569204
330  0.370393  0.810245  0.362469  0.203396  0.452469
331  0.406575  0.490045  0.492634  0.669368  0.024355
332  0.257022  0.572599  0.404611  0.880945  0.426001
333  0.663787  0.335064  0.499930  0.813554  0.042426

[334 rows x 5 columns]

In [17]:
newdf.loc[0,'A']=6554

In [18]:
newdf

            A         B         C         D         E
0        6554  0.600837  0.532238  0.302723  0.115555
1    0.382473  0.276835  0.670707  0.201305  0.728110
2       Ayush  0.689297  0.162800  0.011255  0.439908
3    0.821584  0.023659  0.979987  0.282774  0.155972
4    0.658512  0.851439  0.118980  0.708024  0.985464
..        ...       ...       ...       ...       ...
329  0.258052  0.083932  0.083910  0.091362  0.569204
330  0.370393  0.810245  0.362469  0.203396  0.452469
331  0.406575  0.490045  0.492634  0.669368  0.024355
332  0.257022  0.572599  0.404611  0.880945  0.426001
333  0.663787  0.335064  0.499930  0.813554  0.042426

[334 rows x 5 columns]

In [19]:
newdf.drop(0,axis=0)

            A         B         C         D         E
1    0.382473  0.276835  0.670707  0.201305  0.728110
2       Ayush  0.689297  0.162800  0.011255  0.439908
3    0.821584  0.023659  0.979987  0.282774  0.155972
4    0.658512  0.851439  0.118980  0.708024  0.985464
5    0.549551  0.567473  0.976715  0.672992  0.275604
..        ...       ...       ...       ...       ...
329  0.258052  0.083932  0.083910  0.091362  0.569204
330  0.370393  0.810245  0.362469  0.203396  0.452469
331  0.406575  0.490045  0.492634  0.669368  0.024355
332  0.257022  0.572599  0.404611  0.880945  0.426001
333  0.663787  0.335064  0.499930  0.813554  0.042426

[333 rows x 5 columns]

In [20]:
newdf

            A         B         C         D         E
0        6554  0.600837  0.532238  0.302723  0.115555
1    0.382473  0.276835  0.670707  0.201305  0.728110
2       Ayush  0.689297  0.162800  0.011255  0.439908
3    0.821584  0.023659  0.979987  0.282774  0.155972
4    0.658512  0.851439  0.118980  0.708024  0.985464
..        ...       ...       ...       ...       ...
329  0.258052  0.083932  0.083910  0.091362  0.569204
330  0.370393  0.810245  0.362469  0.203396  0.452469
331  0.406575  0.490045  0.492634  0.669368  0.024355
332  0.257022  0.572599  0.404611  0.880945  0.426001
333  0.663787  0.335064  0.499930  0.813554  0.042426

[334 rows x 5 columns]

In [21]:
newdf.drop(0,axis=0,inplace=True)

In [22]:
newdf

            A         B         C         D         E
1    0.382473  0.276835  0.670707  0.201305  0.728110
2       Ayush  0.689297  0.162800  0.011255  0.439908
3    0.821584  0.023659  0.979987  0.282774  0.155972
4    0.658512  0.851439  0.118980  0.708024  0.985464
5    0.549551  0.567473  0.976715  0.672992  0.275604
..        ...       ...       ...       ...       ...
329  0.258052  0.083932  0.083910  0.091362  0.569204
330  0.370393  0.810245  0.362469  0.203396  0.452469
331  0.406575  0.490045  0.492634  0.669368  0.024355
332  0.257022  0.572599  0.404611  0.880945  0.426001
333  0.663787  0.335064  0.499930  0.813554  0.042426

[333 rows x 5 columns]

In [23]:
newdf.loc[[1,2],['A','B']]

          A         B
1  0.382473  0.276835
2     Ayush  0.689297

In [24]:
newdf.loc[:,['A','B']]

            A         B
1    0.382473  0.276835
2       Ayush  0.689297
3    0.821584  0.023659
4    0.658512  0.851439
5    0.549551  0.567473
..        ...       ...
329  0.258052  0.083932
330  0.370393  0.810245
331  0.406575  0.490045
332  0.257022  0.572599
333  0.663787  0.335064

[333 rows x 2 columns]

In [25]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.382473  0.276835  0.670707  0.201305  0.728110
2     Ayush  0.689297  0.162800  0.011255  0.439908

In [28]:
newdf.loc[(newdf['B']<0.3)]

            A         B         C         D         E
1    0.382473  0.276835  0.670707  0.201305  0.728110
3    0.821584  0.023659  0.979987  0.282774  0.155972
6    0.643869  0.277960  0.084970  0.592636  0.479976
11   0.703198  0.268844  0.666749  0.684140  0.412742
13   0.226659  0.170804  0.322276  0.203726  0.632863
..        ...       ...       ...       ...       ...
320  0.836926  0.087272  0.166141  0.278984  0.503229
322   0.54909  0.258399  0.667837  0.448599  0.952279
323   0.26044  0.077741  0.568864  0.186011  0.882829
328  0.324299  0.202162  0.405910  0.373743  0.676513
329  0.258052  0.083932  0.083910  0.091362  0.569204

[103 rows x 5 columns]

In [29]:
newdf.loc[(newdf['B']<0.3) & (newdf['D']>0.1)]

            A         B         C         D         E
1    0.382473  0.276835  0.670707  0.201305  0.728110
3    0.821584  0.023659  0.979987  0.282774  0.155972
6    0.643869  0.277960  0.084970  0.592636  0.479976
11   0.703198  0.268844  0.666749  0.684140  0.412742
13   0.226659  0.170804  0.322276  0.203726  0.632863
..        ...       ...       ...       ...       ...
317  0.586151  0.187752  0.723825  0.960143  0.920144
320  0.836926  0.087272  0.166141  0.278984  0.503229
322   0.54909  0.258399  0.667837  0.448599  0.952279
323   0.26044  0.077741  0.568864  0.186011  0.882829
328  0.324299  0.202162  0.405910  0.373743  0.676513

[89 rows x 5 columns]

In [30]:
newdf.iloc[[0,5],[1,2]]

          B         C
1  0.276835  0.670707
6  0.277960  0.084970

In [31]:
newdf.reset_index()

     index         A         B         C         D         E
0        1  0.382473  0.276835  0.670707  0.201305  0.728110
1        2     Ayush  0.689297  0.162800  0.011255  0.439908
2        3  0.821584  0.023659  0.979987  0.282774  0.155972
3        4  0.658512  0.851439  0.118980  0.708024  0.985464
4        5  0.549551  0.567473  0.976715  0.672992  0.275604
..     ...       ...       ...       ...       ...       ...
328    329  0.258052  0.083932  0.083910  0.091362  0.569204
329    330  0.370393  0.810245  0.362469  0.203396  0.452469
330    331  0.406575  0.490045  0.492634  0.669368  0.024355
331    332  0.257022  0.572599  0.404611  0.880945  0.426001
332    333  0.663787  0.335064  0.499930  0.813554  0.042426

[333 rows x 6 columns]

In [32]:
newdf.reset_index(drop=True)

            A         B         C         D         E
0    0.382473  0.276835  0.670707  0.201305  0.728110
1       Ayush  0.689297  0.162800  0.011255  0.439908
2    0.821584  0.023659  0.979987  0.282774  0.155972
3    0.658512  0.851439  0.118980  0.708024  0.985464
4    0.549551  0.567473  0.976715  0.672992  0.275604
..        ...       ...       ...       ...       ...
328  0.258052  0.083932  0.083910  0.091362  0.569204
329  0.370393  0.810245  0.362469  0.203396  0.452469
330  0.406575  0.490045  0.492634  0.669368  0.024355
331  0.257022  0.572599  0.404611  0.880945  0.426001
332  0.663787  0.335064  0.499930  0.813554  0.042426

[333 rows x 5 columns]

In [33]:
newdf['B'].isnull()

1      False
2      False
3      False
4      False
5      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 333, dtype: bool

In [34]:
newdf.loc[:,['B']]=pd.NA

/var/folders/9j/t606lw892r3brbxnx5wm0_c40000gn/T/ipykernel_32019/2641648599.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '<NA>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf.loc[:,['B']]=pd.NA

In [35]:
newdf

            A     B         C         D         E
1    0.382473  <NA>  0.670707  0.201305  0.728110
2       Ayush  <NA>  0.162800  0.011255  0.439908
3    0.821584  <NA>  0.979987  0.282774  0.155972
4    0.658512  <NA>  0.118980  0.708024  0.985464
5    0.549551  <NA>  0.976715  0.672992  0.275604
..        ...   ...       ...       ...       ...
329  0.258052  <NA>  0.083910  0.091362  0.569204
330  0.370393  <NA>  0.362469  0.203396  0.452469
331  0.406575  <NA>  0.492634  0.669368  0.024355
332  0.257022  <NA>  0.404611  0.880945  0.426001
333  0.663787  <NA>  0.499930  0.813554  0.042426

[333 rows x 5 columns]

In [36]:
newdf['B'].isnull()

1      True
2      True
3      True
4      True
5      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 333, dtype: bool

In [37]:
#as per the new pandas update, a series can't upgrade to object dtype if you just change the datatype of any one value.
#you need to manually do this and then you can have multiple values in that series.
newdf['A'] = newdf['A'].astype(object)
newdf.loc[2, 'A'] = "Ayush"