In [2]:
import numpy as np
import pandas as pd

In [11]:
dict1 = {"name":["harry","rohan","ayush","anshul"],"marks":[92,34,56,76],"city":["Bangalore","Kolkata","Jaipur","Delhi"]}

In [12]:
df = pd.DataFrame(dict1)

In [13]:
df

     name  marks       city
0   harry     92  Bangalore
1   rohan     34    Kolkata
2   ayush     56     Jaipur
3  anshul     76      Delhi

In [14]:
df.to_csv('friends.csv')

In [15]:
df.to_csv('friends.csv',index=False)

In [16]:
df.head(1)

    name  marks       city
0  harry     92  Bangalore

In [17]:
df.tail(1)

     name  marks   city
3  anshul     76  Delhi

In [18]:
df.describe()

          marks
count   4.00000
mean   64.50000
std    25.10644
min    34.00000
25%    50.50000
50%    66.00000
75%    80.00000
max    92.00000

In [19]:
testdf = pd.read_csv('pandas_test.csv')

In [20]:
testdf['Variable_name']

0                                           Total income
1        Sales, government funding, grants and subsidies
2                      Interest, dividends and donations
3                                   Non-operating income
4                                      Total expenditure
                              ...
55615                                        Quick ratio
55616                Margin on sales of goods for resale
55617                                   Return on equity
55618                             Return on total assets
55619                              Liabilities structure
Name: Variable_name, Length: 55620, dtype: object

In [21]:
testdf['Variable_name'][1]

'Sales, government funding, grants and subsidies'

In [22]:
testdf['Variable_name'][1] = "test"

/var/folders/9j/t606lw892r3brbxnx5wm0_c40000gn/T/ipykernel_30111/1151273434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdf['Variable_name'][1] = "test"

In [23]:
testdf.to_csv("changed_value.csv")

In [24]:
df.index = ['first','second','third','fourth']

In [25]:
df

          name  marks       city
first    harry     92  Bangalore
second   rohan     34    Kolkata
third    ayush     56     Jaipur
fourth  anshul     76      Delhi

In [26]:
ser = pd.Series(np.random.rand(34))

In [27]:
ser

0     0.585762
1     0.450238
2     0.198212
3     0.388204
4     0.233900
5     0.540667
6     0.600742
7     0.750375
8     0.780009
9     0.088769
10    0.518973
11    0.218415
12    0.646983
13    0.118979
14    0.398701
15    0.035873
16    0.467366
17    0.967677
18    0.240082
19    0.164803
20    0.094235
21    0.982982
22    0.030227
23    0.543949
24    0.725200
25    0.409502
26    0.104984
27    0.543124
28    0.737186
29    0.535621
30    0.724838
31    0.716080
32    0.342697
33    0.234089
dtype: float64

In [29]:
newdf = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [30]:
newdf

            0         1         2         3         4
0    0.591077  0.109909  0.353345  0.596011  0.677463
1    0.318877  0.653349  0.111920  0.933137  0.943522
2    0.678614  0.436555  0.026035  0.193479  0.643651
3    0.738135  0.051891  0.583331  0.850434  0.907443
4    0.875572  0.919517  0.826310  0.797471  0.586023
..        ...       ...       ...       ...       ...
329  0.488731  0.492727  0.268778  0.201649  0.067377
330  0.640698  0.254386  0.351891  0.286848  0.230728
331  0.497888  0.757556  0.298361  0.800963  0.475171
332  0.603253  0.703770  0.638823  0.043474  0.827963
333  0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [31]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [32]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [33]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [34]:
newdf.to_numpy()

array([[0.5910767 , 0.10990939, 0.35334452, 0.59601116, 0.67746283],
       [0.31887699, 0.65334861, 0.11191963, 0.9331367 , 0.94352243],
       [0.67861448, 0.43655543, 0.02603499, 0.19347875, 0.64365085],
       ...,
       [0.49788818, 0.75755556, 0.29836055, 0.80096314, 0.47517057],
       [0.60325253, 0.70376973, 0.63882251, 0.04347365, 0.82796297],
       [0.62180521, 0.53521609, 0.5870525 , 0.10519457, 0.50660459]],
      shape=(334, 5))

In [35]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.591077,0.318877,0.678614,0.738135,0.875572,0.547247,0.724115,0.242573,0.245552,0.362150,...,0.974629,0.797768,0.711204,0.155028,0.609093,0.488731,0.640698,0.497888,0.603253,0.621805
1,0.109909,0.653349,0.436555,0.051891,0.919517,0.790148,0.241200,0.733293,0.070667,0.251928,...,0.924606,0.790376,0.128101,0.159440,0.420889,0.492727,0.254386,0.757556,0.703770,0.535216
2,0.353345,0.111920,0.026035,0.583331,0.826310,0.869892,0.357277,0.411417,0.824159,0.444561,...,0.148481,0.613034,0.936903,0.011568,0.779610,0.268778,0.351891,0.298361,0.638823,0.587053
3,0.596011,0.933137,0.193479,0.850434,0.797471,0.545217,0.634054,0.218302,0.055244,0.748255,...,0.533198,0.936230,0.076084,0.276720,0.715775,0.201649,0.286848,0.800963,0.043474,0.105195
4,0.677463,0.943522,0.643651,0.907443,0.586023,0.123221,0.132626,0.229163,0.472015,0.428863,...,0.792377,0.243767,0.123906,0.207881,0.263097,0.067377,0.230728,0.475171,0.827963,0.506605

In [36]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.621805  0.535216  0.587053  0.105195  0.506605
332  0.603253  0.703770  0.638823  0.043474  0.827963
331  0.497888  0.757556  0.298361  0.800963  0.475171
330  0.640698  0.254386  0.351891  0.286848  0.230728
329  0.488731  0.492727  0.268778  0.201649  0.067377
..        ...       ...       ...       ...       ...
4    0.875572  0.919517  0.826310  0.797471  0.586023
3    0.738135  0.051891  0.583331  0.850434  0.907443
2    0.678614  0.436555  0.026035  0.193479  0.643651
1    0.318877  0.653349  0.111920  0.933137  0.943522
0    0.591077  0.109909  0.353345  0.596011  0.677463

[334 rows x 5 columns]

In [37]:
newdf2 = newdf

In [44]:
newdf2[0][0] = 5773

/var/folders/9j/t606lw892r3brbxnx5wm0_c40000gn/T/ipykernel_30111/2127336885.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 5773

In [45]:
newdf2

               0         1         2         3         4
0    5773.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [46]:
newdf

               0         1         2         3         4
0    5773.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [47]:
newdf2 = newdf.copy()

In [48]:
newdf2[0][0]=5772

/var/folders/9j/t606lw892r3brbxnx5wm0_c40000gn/T/ipykernel_30111/1895319805.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=5772

In [49]:
newdf2

               0         1         2         3         4
0    5772.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [50]:
newdf

               0         1         2         3         4
0    5773.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [51]:
newdf.columns = list("ABCDE")

In [52]:
newdf

               A         B         C         D         E
0    5773.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [53]:
newdf.loc[0,'A']=6554

In [54]:
newdf

               A         B         C         D         E
0    6554.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [56]:
newdf.drop(0,axis=0)

            A         B         C         D         E
1    0.318877  0.653349  0.111920  0.933137  0.943522
2    0.678614  0.436555  0.026035  0.193479  0.643651
3    0.738135  0.051891  0.583331  0.850434  0.907443
4    0.875572  0.919517  0.826310  0.797471  0.586023
5    0.547247  0.790148  0.869892  0.545217  0.123221
..        ...       ...       ...       ...       ...
329  0.488731  0.492727  0.268778  0.201649  0.067377
330  0.640698  0.254386  0.351891  0.286848  0.230728
331  0.497888  0.757556  0.298361  0.800963  0.475171
332  0.603253  0.703770  0.638823  0.043474  0.827963
333  0.621805  0.535216  0.587053  0.105195  0.506605

[333 rows x 5 columns]

In [57]:
newdf

               A         B         C         D         E
0    6554.000000  0.109909  0.353345  0.596011  0.677463
1       0.318877  0.653349  0.111920  0.933137  0.943522
2       0.678614  0.436555  0.026035  0.193479  0.643651
3       0.738135  0.051891  0.583331  0.850434  0.907443
4       0.875572  0.919517  0.826310  0.797471  0.586023
..           ...       ...       ...       ...       ...
329     0.488731  0.492727  0.268778  0.201649  0.067377
330     0.640698  0.254386  0.351891  0.286848  0.230728
331     0.497888  0.757556  0.298361  0.800963  0.475171
332     0.603253  0.703770  0.638823  0.043474  0.827963
333     0.621805  0.535216  0.587053  0.105195  0.506605

[334 rows x 5 columns]

In [58]:
newdf.drop(0,axis=0,inplace=True)

In [59]:
newdf

            A         B         C         D         E
1    0.318877  0.653349  0.111920  0.933137  0.943522
2    0.678614  0.436555  0.026035  0.193479  0.643651
3    0.738135  0.051891  0.583331  0.850434  0.907443
4    0.875572  0.919517  0.826310  0.797471  0.586023
5    0.547247  0.790148  0.869892  0.545217  0.123221
..        ...       ...       ...       ...       ...
329  0.488731  0.492727  0.268778  0.201649  0.067377
330  0.640698  0.254386  0.351891  0.286848  0.230728
331  0.497888  0.757556  0.298361  0.800963  0.475171
332  0.603253  0.703770  0.638823  0.043474  0.827963
333  0.621805  0.535216  0.587053  0.105195  0.506605

[333 rows x 5 columns]

In [60]:
newdf.loc[[1,2],['A','B']]

          A         B
1  0.318877  0.653349
2  0.678614  0.436555

In [61]:
newdf.loc[:,['A','B']]

            A         B
1    0.318877  0.653349
2    0.678614  0.436555
3    0.738135  0.051891
4    0.875572  0.919517
5    0.547247  0.790148
..        ...       ...
329  0.488731  0.492727
330  0.640698  0.254386
331  0.497888  0.757556
332  0.603253  0.703770
333  0.621805  0.535216

[333 rows x 2 columns]

In [62]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.318877  0.653349  0.111920  0.933137  0.943522
2  0.678614  0.436555  0.026035  0.193479  0.643651

In [63]:
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
7    0.242573  0.733293  0.411417  0.218302  0.229163
8    0.245552  0.070667  0.824159  0.055244  0.472015
14   0.151065  0.381587  0.992268  0.952952  0.400736
20   0.144527  0.647285  0.704944  0.336692  0.862755
25   0.093972  0.580277  0.457923  0.179161  0.965378
..        ...       ...       ...       ...       ...
313  0.203062  0.269935  0.924786  0.326445  0.235699
316  0.079586  0.208538  0.899928  0.641444  0.327857
317  0.271484  0.674554  0.691111  0.945174  0.451012
321  0.227842  0.068827  0.087579  0.028361  0.281707
327  0.155028  0.159440  0.011568  0.276720  0.207881

[96 rows x 5 columns]

In [65]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         E
7    0.242573  0.733293  0.411417  0.218302  0.229163
8    0.245552  0.070667  0.824159  0.055244  0.472015
14   0.151065  0.381587  0.992268  0.952952  0.400736
20   0.144527  0.647285  0.704944  0.336692  0.862755
25   0.093972  0.580277  0.457923  0.179161  0.965378
..        ...       ...       ...       ...       ...
305  0.034602  0.513598  0.758930  0.648758  0.443282
310  0.217232  0.007955  0.331525  0.905838  0.546897
313  0.203062  0.269935  0.924786  0.326445  0.235699
316  0.079586  0.208538  0.899928  0.641444  0.327857
317  0.271484  0.674554  0.691111  0.945174  0.451012

[86 rows x 5 columns]

In [66]:
newdf.iloc[[0,5],[1,2]]

          B         C
1  0.653349  0.111920
6  0.241200  0.357277

In [67]:
newdf.reset_index()

     index         A         B         C         D         E
0        1  0.318877  0.653349  0.111920  0.933137  0.943522
1        2  0.678614  0.436555  0.026035  0.193479  0.643651
2        3  0.738135  0.051891  0.583331  0.850434  0.907443
3        4  0.875572  0.919517  0.826310  0.797471  0.586023
4        5  0.547247  0.790148  0.869892  0.545217  0.123221
..     ...       ...       ...       ...       ...       ...
328    329  0.488731  0.492727  0.268778  0.201649  0.067377
329    330  0.640698  0.254386  0.351891  0.286848  0.230728
330    331  0.497888  0.757556  0.298361  0.800963  0.475171
331    332  0.603253  0.703770  0.638823  0.043474  0.827963
332    333  0.621805  0.535216  0.587053  0.105195  0.506605

[333 rows x 6 columns]

In [68]:
newdf.reset_index(drop=True)

            A         B         C         D         E
0    0.318877  0.653349  0.111920  0.933137  0.943522
1    0.678614  0.436555  0.026035  0.193479  0.643651
2    0.738135  0.051891  0.583331  0.850434  0.907443
3    0.875572  0.919517  0.826310  0.797471  0.586023
4    0.547247  0.790148  0.869892  0.545217  0.123221
..        ...       ...       ...       ...       ...
328  0.488731  0.492727  0.268778  0.201649  0.067377
329  0.640698  0.254386  0.351891  0.286848  0.230728
330  0.497888  0.757556  0.298361  0.800963  0.475171
331  0.603253  0.703770  0.638823  0.043474  0.827963
332  0.621805  0.535216  0.587053  0.105195  0.506605

[333 rows x 5 columns]

In [69]:
newdf['B'].isnull()

1      False
2      False
3      False
4      False
5      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 333, dtype: bool

In [71]:
newdf.loc[:,['B']]=None

In [72]:
newdf

            A     B         C         D         E
1    0.318877  None  0.111920  0.933137  0.943522
2    0.678614  None  0.026035  0.193479  0.643651
3    0.738135  None  0.583331  0.850434  0.907443
4    0.875572  None  0.826310  0.797471  0.586023
5    0.547247  None  0.869892  0.545217  0.123221
..        ...   ...       ...       ...       ...
329  0.488731  None  0.268778  0.201649  0.067377
330  0.640698  None  0.351891  0.286848  0.230728
331  0.497888  None  0.298361  0.800963  0.475171
332  0.603253  None  0.638823  0.043474  0.827963
333  0.621805  None  0.587053  0.105195  0.506605

[333 rows x 5 columns]

In [73]:
newdf['B'].isnull()

1      True
2      True
3      True
4      True
5      True
       ...
329    True
330    True
331    True
332    True
333    True
Name: B, Length: 333, dtype: bool